// LOGIN/REGISTER SECTION
export const LOGINING = 'LOGINING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const IS_SIGNED_IN = 'IS_SIGNED_IN';
export const GET_MY_USER_ID = 'GET_MY_USER_ID';
export const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
export const HANDLE_EMAIL_CHANGE = 'HANDLE_EMAIL_CHANGE';
export const HANDLE_PASSWORD_CHANGE = 'HANDLE_PASSWORD_CHANGE';

// ORG ID SECTION
export const CREATE_ORG_ID_ADDRESS = 'CREATE_ORG_ID_ADDRESS';
export const CREATE_ORG_ID = 'CREATE_ORG_ID';
export const CALCULATE_ORG_ID_HASH = 'CALCULATE_ORG_ID_HASH';
export const GET_ALL_ORG_ID = 'GET_ALL_ORG_ID';
export const GET_SELECTED_ORG_ID = 'GET_SELECTED_ORG_ID';


// MOTION SENSORS SECTION
export const SET_X = 'SET_X';
export const SET_Y = 'SET_Y';
export const SET_Z = 'SET_Z';
export const SET_ACCELEROMETER_HISTORY = 'SET_ACCELEROMETER_HISTORY';
export const CALCULATE_BPF = 'CALCULATE_BPF';
export const SET_ACCELEROMETER_DATA = 'SET_ACCELEROMETER_DATA';